services:
  db:
    container_name: relay-db
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.relay/data:/var/lib/postgresql/data
    networks:
      relay-net:
        aliases:
          - relay-db
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
  relay:
    container_name: relay
    build:
      context: .
      dockerfile: ./.docker/relay/Dockerfile
    networks:
      relay-net:
        aliases:
          - relay
    ports:
      - "3001:3001"
    restart: on-failure
    healthcheck:
      test: "exit 0"
  relay_supabase:
    container_name: relay_supabase
    build:
      context: .
      dockerfile: ./.docker/relay/Dockerfile
    networks:
      relay-net:
        aliases:
          - relay-supabase
      supabase_default:
        aliases:
          - relay-supabase
    ports:
      - "3001:3001"
    restart: on-failure
    healthcheck:
      test: "exit 0"
  server:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.relay/nginx/conf/:/etc/nginx/conf.d/:ro
      - certs_www_volume:/var/www/certbot/:ro
      - certs_conf_volume:/etc/nginx/ssl/:ro
    networks:
      relay-net:
        aliases:
          - relay-server
      supabase_default:
        aliases:
          - relay-server
  server-cert:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.relay/nginx_cert/conf/:/etc/nginx/conf.d/:ro
      - certs_www_volume:/var/www/certbot/:ro
      - certs_conf_volume:/etc/nginx/ssl/:ro
    networks:
      relay-net:
        aliases:
          - relay-server-cert
  certbot-renew:
    image: certbot/certbot:latest
    volumes:
      - certs_www_volume:/var/www/certbot/:rw
      - certs_conf_volume:/etc/letsencrypt/:rw

volumes:
  certs_www_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.relay/certbot/www/
  certs_conf_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.relay/certbot/conf/

networks:
  relay-net:
    name: relay-net
  supabase_default:
    external: true
